# Copyright (c) Meta Platforms, Inc. and affiliates.

load("../../defs.bzl", "relative_headers", "zs_library")

oncall("data_compression")

zs_library(
    name = "csv_parser",
    srcs = glob(
        [
            "*.c",
            "*.cpp",
        ],
        exclude = ["tests/*"],
    ),
    headers = relative_headers(
        glob(
            ["*.h"],
        )
    )
    | {
        header: header
        for header in [
            "csv_lexer.h",
            "csv_parser.h",
            "csv_profile.h",
            "csv_segmenter.h",
        ]
    },
    exported_deps = [
        "../..:zstronglib",
        "../shared_components:numeric_graphs",
        "../shared_components:string_graphs",
    ],
)
