# Copyright (c) Meta Platforms, Inc. and affiliates.

load("../../../defs.bzl", "zs_cxxlibrary")

oncall("data_compression")

zs_cxxlibrary(
    name = "sample_collection",
    srcs = [
        "introspection_hooks.cpp",
        "training_sample_collector.cpp",
    ],
    headers = {
        "introspection_hooks.h": "introspection_hooks.h",
        "tools/training/sample_collection/introspection_hooks.h": "introspection_hooks.h",
        "tools/training/sample_collection/training_sample_collector.h": "training_sample_collector.h",
        "training_sample_collector.h": "training_sample_collector.h",
    },
    exported_deps = [
        "../..:io",
        "../..:logger",
        "../../..:common",
        "../../..:zstronglib",
        "../../../cpp:openzl_cpp",
        "../utils:training_utils",
    ],
)
