# Copyright (c) Meta Platforms, Inc. and affiliates.

load("@fbcode_macros//build_defs:protobuf_library.bzl", "protobuf_library")
load("../../defs.bzl", "zs_cxxbinary", "zs_cxxlibrary")

oncall("data_compression")

protobuf_library(
    name = "schema",
    srcs = ["schema.proto"],
    langs = [
        "cpp",
    ],
)

zs_cxxlibrary(
    name = "utils",
    srcs = [
        "DescriptorLoader.cpp",
        "DynamicMessageHelper.cpp",
        "StringWriter.cpp",
    ],
    headers = {
        "DescriptorLoader.h": "DescriptorLoader.h",
        "DynamicMessageHelper.h": "DynamicMessageHelper.h",
        "StringWriter.h": "StringWriter.h",
        "tools/protobuf/DescriptorLoader.h": "DescriptorLoader.h",
        "tools/protobuf/DynamicMessageHelper.h": "DynamicMessageHelper.h",
        "tools/protobuf/StringReader.h": "StringReader.h",
        "tools/protobuf/StringWriter.h": "StringWriter.h",
        "tools/protobuf/mem.h": "mem.h",
    },
    exported_deps = [
        "../..:zstronglib",
        "fbsource//third-party/protobuf:libprotobuf",
    ],
)

zs_cxxbinary(
    name = "cli",
    srcs = ["cli.cpp"],
    compiler_flags = [
        "-Wno-switch-enum",
        "-Wno-cast-qual",
    ],
    deps = [
        "..:arg",
        "..:io",
        "../../custom_parsers:custom_parsers",
        "../training:train",
        ":schema-cpp",
        ":serialization_utils",
        ":serializer",
    ],
    external_deps = ["protobuf"],
)

zs_cxxlibrary(
    name = "serializer",
    srcs = [
        "ProtoDeserializer.cpp",
        "ProtoSerializer.cpp",
    ],
    headers = {
        "ProtoDeserializer.h": "ProtoDeserializer.h",
        "ProtoSerializer.h": "ProtoSerializer.h",
        "tools/protobuf/ProtoDeserializer.h": "ProtoDeserializer.h",
        "tools/protobuf/ProtoSerializer.h": "ProtoSerializer.h",
        "tools/protobuf/Types.h": "Types.h",
    },
    compiler_flags = [
        "-Wno-switch-enum",
        "-Wno-cast-qual",
    ],
    deps = [
        "../..:zstronglib",
    ],
    exported_deps = [
        "../../cpp:openzl_cpp",
        "fbsource//third-party/protobuf:libprotobuf",
        ":proto_graph",
        ":utils",
    ],
    exported_external_deps = ["protobuf"],
)

zs_cxxlibrary(
    name = "serialization_utils",
    srcs = [
        "serialization_utils.cpp",
    ],
    headers = {
        "serialization_utils.h": "serialization_utils.h",
        "tools/protobuf/serialization_utils.h": "serialization_utils.h",
    },
    exported_deps = [
        ":serializer",
    ],
)

zs_cxxlibrary(
    name = "proto_graph",
    srcs = [
        "ProtoGraph.cpp",
    ],
    headers = {
        "ProtoGraph.h": "ProtoGraph.h",
        "tools/protobuf/ProtoGraph.h": "ProtoGraph.h",
    },
    compiler_flags = [
        "-Wno-switch-enum",
        "-Wno-cast-qual",
    ],
    deps = [
        "../..:zstronglib",
    ],
)
