# Copyright (c) Meta Platforms, Inc. and affiliates.

load("../../defs.bzl", "zs_cxxlibrary")

oncall("data_compression")

zs_cxxlibrary(
    name = "numeric_graphs",
    srcs = ["numeric_graphs.cpp"],
    headers = {"custom_parsers/shared_components/numeric_graphs.h": "numeric_graphs.h", "numeric_graphs.h": "numeric_graphs.h"},
    exported_deps = [
        "../..:zstronglib",
    ],
)

zs_cxxlibrary(
    name = "string_graphs",
    srcs = ["string_graphs.cpp"],
    headers = {"custom_parsers/shared_components/string_graphs.h": "string_graphs.h", "string_graphs.h": "string_graphs.h"},
    exported_deps = [
        "../..:zstronglib",
    ],
)

zs_cxxlibrary(
    name = "clustering",
    srcs = [
        "clustering.cpp",
    ],
    headers = {
        "clustering.h": "clustering.h",
        "custom_parsers/shared_components/clustering.h": "clustering.h",
    },
    exported_deps = [
        "../..:zstronglib",
        ":numeric_graphs",
        ":string_graphs",
    ],
)
