# Copyright (c) Meta Platforms, Inc. and affiliates.

load("../../../defs.bzl", "relative_headers", "zs_cxxbinary", "zs_cxxlibrary")

oncall("data_compression")

zs_cxxlibrary(
    name = "lib",
    srcs = glob(
        [
            "*.cpp",
            "tokenizer/*.cpp",
            "grouper/*.cpp",
            "parser/*.cpp",
            "codegen/*.cpp",
            "semantic_analyzer/*.cpp",
            "optimizer/*.cpp",
        ],
        exclude = ["main.cpp"],
    ),
    headers = relative_headers(
        glob([
            "*.h",
            "tokenizer/*.h",
            "grouper/*.h",
            "parser/*.h",
            "codegen/*.h",
            "semantic_analyzer/*.h",
            "optimizer/*.h",
        ])
    )
    | {
        header: header
        for header in [
            "Compiler.h",
            "Exception.h",
            "Logger.h",
            "Source.h",
            "Syntax.h",
            "codegen/CodeGenerator.h",
            "codegen/RegisterAllocator.h",
            "grouper/Grouper.h",
            "grouper/Grouping.h",
            "optimizer/ConstFoldPass.h",
            "optimizer/DeadVarPass.h",
            "optimizer/Optimizer.h",
            "parser/AST.h",
            "parser/Grammar.h",
            "parser/Ops.h",
            "parser/Parser.h",
            "semantic_analyzer/SemanticAnalyzer.h",
            "tokenizer/Token.h",
            "tokenizer/Tokenizer.h",
        ]
    },
    exported_deps = [
        "../../../cpp:openzl_cpp",
    ],
)

zs_cxxbinary(
    name = "compiler",
    srcs = ["main.cpp"],
    deps = [
        "../../../tools:io",
        ":lib",
    ],
)
