# Copyright (c) Meta Platforms, Inc. and affiliates.

load("../../defs.bzl", "relative_headers", "zs_library")

oncall("data_compression")

zs_library(
    name = "profile",
    srcs = glob([
        "*.c",
        "*.cpp",
    ]),
    headers = relative_headers(
        glob([
            "*.h",
        ])
    )
    | {"sddl_profile.h": "sddl_profile.h"},
    deps = [
        "../../tools/sddl/compiler:lib",
        "../shared_components:clustering",
    ],
    exported_deps = [
        "../..:zstronglib",
    ],
)
