# Copyright (c) Meta Platforms, Inc. and affiliates.

load("../../../defs.bzl", "relative_headers", "zs_cxxbinary", "zs_cxxlibrary")

oncall("data_compression")

zs_cxxlibrary(
    name = "lib",
    srcs = glob(
        [
            "*.cpp",
        ],
        exclude = ["main.cpp"],
    ),
    headers = relative_headers(
        glob([
            "*.h",
        ])
    )
    | {
        header: header
        for header in [
            "AST.h",
            "Compiler.h",
            "Exception.h",
            "Grammar.h",
            "Grouper.h",
            "Grouping.h",
            "Logger.h",
            "Parser.h",
            "Serializer.h",
            "Source.h",
            "Syntax.h",
            "Token.h",
            "Tokenizer.h",
        ]
    },
    exported_deps = [
        "../../../cpp:openzl_cpp",
    ],
)

zs_cxxbinary(
    name = "compiler",
    srcs = ["main.cpp"],
    deps = [
        ":lib",
    ],
)
