# Copyright (c) Meta Platforms, Inc. and affiliates.

load("../../defs.bzl", "zs_cxxlibrary")

oncall("data_compression")

zs_cxxlibrary(
    name = "args",
    srcs = ["ArgsUtils.cpp"],
    headers = {
        "ArgsUtils.h": "ArgsUtils.h",
        "cli/args/ArgsUtils.h": "ArgsUtils.h",
        "cli/args/BenchmarkArgs.h": "BenchmarkArgs.h",
        "cli/args/CompressArgs.h": "CompressArgs.h",
        "cli/args/DecompressArgs.h": "DecompressArgs.h",
        "cli/args/GlobalArgs.h": "GlobalArgs.h",
        "cli/args/InspectArgs.h": "InspectArgs.h",
        "cli/args/ListProfilesArgs.h": "ListProfilesArgs.h",
        "cli/args/TrainArgs.h": "TrainArgs.h",
    },
    exported_deps = [
        "..:cmd",
        "../../cpp:openzl_cpp",
        "../../custom_parsers:custom_parsers",
        "../../tools:arg",
        "../../tools:io",
        "../../tools/training:train_common",
        "../../tools/training/utils:training_utils",
        "../utils:utils",
    ],
)
