# Copyright (c) Meta Platforms, Inc. and affiliates.

load("../../defs.bzl", "zs_cxxlibrary")

oncall("data_compression")

zs_cxxlibrary(
    name = "zstrong_gbt_predictor",
    srcs = ["zstrong_gbt_predictor.cpp"],
    headers = {"tools/gbt_predictor/zstrong_gbt_predictor.h": "zstrong_gbt_predictor.h", "zstrong_gbt_predictor.h": "zstrong_gbt_predictor.h"},
    compiler_flags = ["-Wno-float-equal"],
    strict_conversions = False,
    deps = [
        "../..:zstronglib",
    ],
    exported_deps = [
        "//folly:dynamic",
        "//folly/json:dynamic",
    ],
)
