# Copyright (c) Meta Platforms, Inc. and affiliates.

load("../../defs.bzl", "zs_cxxlibrary")

oncall("data_compression")

zs_cxxlibrary(
    name = "thrift_types",
    headers = ["thrift_types.h"],
)

zs_cxxlibrary(
    name = "thrift_compact_reader",
    srcs = ["thrift_compact_reader.cpp"],
    headers = {"custom_parsers/parquet/thrift_compact_reader.h": "thrift_compact_reader.h", "thrift_compact_reader.h": "thrift_compact_reader.h"},
    exported_deps = [
        "../..:zstronglib",
        ":thrift_types",
    ],
)

zs_cxxlibrary(
    name = "parquet_metadata",
    srcs = ["parquet_metadata.cpp"],
    headers = {"custom_parsers/parquet/parquet_metadata.h": "parquet_metadata.h", "parquet_metadata.h": "parquet_metadata.h"},
    exported_deps = [
        ":thrift_compact_reader",
        ":thrift_types",
    ],
)

zs_cxxlibrary(
    name = "parquet_lexer",
    srcs = ["parquet_lexer.cpp"],
    headers = {"custom_parsers/parquet/parquet_lexer.h": "parquet_lexer.h", "parquet_lexer.h": "parquet_lexer.h"},
    deps = [
        "../..:zstronglib",
        ":parquet_metadata",
    ],
)

zs_cxxlibrary(
    name = "parquet_graph",
    srcs = ["parquet_graph.c"],
    headers = {"custom_parsers/parquet/parquet_graph.h": "parquet_graph.h", "parquet_graph.h": "parquet_graph.h"},
    deps = [
        "../..:zstronglib",
        ":parquet_lexer",
    ],
)
